apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: test
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      hostname: ubuntu-test1
      containers:
        - name: ubuntu-container
          image: ubuntu
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          command: ["/bin/sh"]
          args:
            - "-c"
            - "echo This is an array of args; while true; do echo .; sleep 1; done"
          env:
            - name: MYENVVAR
              value: "This is a string"
            - name: CMENV1
              valueFrom:
                configMapKeyRef:
                  name: cm-example
                  key: example.property.1
            - name: CMENVFile
              valueFrom:
                configMapKeyRef:
                  name: cm-example 
                  key: example.property.file
            - name: CMENV2
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: key1
