apiVersion: v1
kind: Service
metadata:
  name: headless-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
     environment: dev
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80