apiVersion: v1
kind: Pod
metadata:
  name: pod-with-ambassador
spec:
  containers:
  - name: app-container
    image: curlimages/curl
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: ambassador-container
    image: nginx
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx/conf.d
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: nginx-conf 
    configMap:
      name: nginx-lb