apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-lb
data:
  default.conf: upstream ambassador { server nginx-svc1; server nginx-svc2;} server { listen 80; server_name localhost; location / {proxy_pass http://ambassador; }} 
