apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: test
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      hostname: ubuntu-test1
      containers:
        - name: ubuntu-container
          image: ubuntu
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          command: ["/bin/sh"]
          args:
            - "-c"
            - "echo This is an array of args; while true; do echo .; sleep 1; done"
          volumeMounts:
            - name: secret-vol-1
              mountPath: "/etc/foo"
              readOnly: true
      volumes:
        - name: secret-vol-1
          secret:
            secretName: mysecret
