apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: my-ns
  labels:
    app: nginx
    environment: qa
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
