apiVersion: batch/v1beta1
kind: Job
metadata:
  name: pi-cron
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      completions: 2
      template:
        metadata:
          name: pi
        spec:
          containers:
          - name: pi
            image: ubuntu
            command: ["/bin/sh"]
            args: ["-c", "date && echo Hello world form Cron Job"]
          restartPolicy: Never
