apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-container
  template:
    metadata:
      labels:
        app: two-container
    spec:
      containers:
      - name: ubuntu-container
        image: ubuntu
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "while true; do echo inside the ubuntu container; sleep 1; done"
      - name: busybox-container
        image: busybox
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "while true; do echo inside the busybox container; sleep 1; done"
