apiVersion: v1
kind: Pod
metadata:
  name: labelpod
  labels:
    environment: staging
    tier: frontend
  annotations:
    someText: "http://my-metadata.com"
spec:
  containers:
  - name: labelcontainer
    image: nginx
    ports:
    - containerPort: 80