apiVersion: v1
kind: LimitRange
metadata:
  name: limit-compute
  namespace: test
spec:
  limits:
    - type: Container
      min:
        cpu: "100m"
        memory: "99Mi"
      max:
        cpu: "800m"
        memory: "1Gi"
      default:
        cpu: "700m"
        memory: "900Mi"
      defaultRequest:
        cpu: "110m"
        memory: "111Mi"
        