apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-resources
  namespace: test
spec:
  hard:
    requests.storage: "5Gi"
    persistentvolumeclaims: "10"
    mySC.storageclass.storage.k8s.io/requests.storage: "2Gi"
    mySC.storageclass.storage.k8s.io/persistentvolumeclaims: "5"
    requests.ephemeral-storage: "1Gi"
    limits.ephemeral-storage: "2Gi"
