apiVersion: v1
kind: Pod
metadata:
  name: pod-sidecar
  labels:
    tier: frontend
spec:
  containers:
  - name: app-container
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - /bin/sh
    args:
      - -c
      - while true; do data >> /var/log/app.txt; sleep 5; done
    volumeMounts:
      - name: shared-logs
        mountPath: /var/log
  - name: sidecar-container
    image: nginx
    ports:
      - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: shared-logs
        mountPath: /usr/share/nginx/html
  volumes:
    - name: shared-logs
      emptyDir: {}

