apiVersion: v1
kind: Pod
metadata:
  name: pod-with-adapter
spec:
  containers:
  - name: app-container
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /var/log/input.txt; sleep 5; done"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: adapter-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do (cat /var/log/input.txt | tail -1) | sed 's/UTC/GMT/g'; sleep 5; done"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: shared-logs 
    emptyDir: {}