apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: my-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu-container
        image: ubuntu
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "echo The Pod is running; while true; do echo.; sleep 1; done"
        volumeMounts:
          - mountPath: /tmp/data
            name: ubuntu-emptydir-storage
      volumes:
        - name: ubuntu-emptydir-storage
          emptyDir: {}
