apiVersion: v1
kind: Pod
metadata:
  name: localhostmysql
  labels:
    app: db
spec:
  containers:
  - image: mysql:8.0-oracle
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    ports:
    - containerPort: 3306
      name: mysql
    volumeMounts:
    - name: mysql-hostpah-storage
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql-hostpah-storage
    hostPath:
      path: "/tmp"
      type: DirectoryOrCreate