apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: my-ns
spec:
  containers:
    - name: curl-container
      image: curlimage/curl:latest
      command: ["sh", "-c", "tail -f /dev/null"]
      securityContext:
        runAsUser: 0
        privileged: true
