apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: my-ns
spec:
  selector:
    app: nginx
  clusterIP: None
  ports:
    - port: 80

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-ss
  namespace: my-ns
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx-svc"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
            - containerPort: 80
