apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin1
  namespace: test

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-rolebind
roleRef:
  kind: ClusterRole
  name: pod-reader
subjects:
  - kind: ServiceAccount
    name: admin1
    namespace: test